---
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: This stack deploys the s3 bucket, cdn and oai for imageR-houessou-com website.

Resources:
# S3 bucket for web static files
  imageRWebBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: 'hpf-imageR-houessou-com-web'
  
  imageRWebBucketOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    DeletionPolicy: Retain
    Properties: 
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Join ['', ['access-identity-', !Ref imageRWebBucket, '.s3.amazonaws.com'] ]

  imageRWebBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DeletionPolicy: Retain
    Properties:
      Bucket: !Ref imageRWebBucket
      PolicyDocument:  
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 's3:GetObject'
            Resource: !Join ['', [!GetAtt 'imageRWebBucket.Arn', '/*'] ]
            Principal: 
              AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${imageRWebBucketOAI}'

  imageRWebBucketCF:
    Type: AWS::CloudFront::Distribution
    DeletionPolicy: Retain
    DependsOn: imageRWebBucket
    Properties:
      DistributionConfig:
        Aliases: 
          - "imageR.houessou.com"
        Comment: !Join ['', ['CDN for ', !Ref imageRWebBucket] ]
        Enabled: 'true'
        DefaultRootObject: 'index.html'
        DefaultCacheBehavior:
          AllowedMethods:
            - HEAD
            - DELETE
            - POST
            - GET
            - OPTIONS
            - PUT
            - PATCH
          ForwardedValues:
            QueryString: 'false'
          TargetOriginId: !Join ['', [!Ref 'imageRWebBucket', '.s3.us-east-1.amazonaws.com'] ]
          ViewerProtocolPolicy: redirect-to-https
        Origins:
          - S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${imageRWebBucketOAI}'
            DomainName: !Join ['', [!Ref 'imageRWebBucket', '.s3.us-east-1.amazonaws.com'] ]
            Id: !Join ['', [!Ref 'imageRWebBucket', '.s3.us-east-1.amazonaws.com'] ]
        ViewerCertificate:
          SslSupportMethod: 'sni-only'
          AcmCertificateArn: !Join [ '', ['arn:aws:acm:', !Ref 'AWS::Region', ':', !Ref 'AWS::AccountId', ':certificate/9aa19f38-e5dd-4555-8c03-db3005220c7e' ] ]

Outputs:
  imageRWebBucket:
    Value: !Ref 'imageRWebBucket' 
    Export:
      Name: !Sub "${AWS::StackName}-imageRWebBucket"
  imageRWebBucketCFDomainName:
    Value: !GetAtt 'imageRWebBucketCF.DomainName' 
    Export:
      Name: !Sub "${AWS::StackName}-imageRWebBucketCFDomainName"