name: deploy imager-houessou-com backend website resources

on:
  push:
      branches: [ main ]
      paths:
        - 'backend/aws/website/**'
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

# sam build 
      - name: sam build
        working-directory: ./backend/aws/website
        run: sam build --use-container -t website.yaml


# sam deploy
      - name: sam deploy
        working-directory: ./backend/aws/website
        run: sam deploy -t website.yaml --no-confirm-changeset --no-fail-on-empty-changeset --stack-name ${{ secrets.WEBSITE_STACK_NAME}} --s3-bucket ${{ secrets.SAM_S3_BUCKET }} --capabilities CAPABILITY_NAMED_IAM --region ${{ secrets.AWS_REGION }}
