name: deploy imager-houessou-com service

on:
  push:
      branches: [ main ]
      paths:
        - 'backend/aws/service/**'
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

# sam build 
      - name: sam build
        working-directory: ./backend/aws/service
        run: sam build -t service.yaml

# Run Unit tests- Specify unit tests here 
     ## - name: Run tests
      ##  run: |
          ## pushd './backend/aws/service'
          ## pip install awscli
          ## python -m pip install --upgrade pip
          ## pip install -r requirements.txt      
          ## python -m nose2 test_getAnalysis.lambda_handler test_analyzeImage.lambda_handler 

# sam deploy
      - name: sam deploy
        working-directory: ./backend/aws/service
        run: sam deploy -t .aws-sam/build/template.yaml --no-confirm-changeset --no-fail-on-empty-changeset --stack-name ${{ secrets.SERVICE_STACK_NAME}} --s3-bucket ${{ secrets.SAM_S3_BUCKET }} --capabilities CAPABILITY_NAMED_IAM --region ${{ secrets.AWS_REGION }}
